### ISSUE TITLE
Provide package for the plugin center

### ISSUE THREAD

**Issue by markiewb** [lsimedia/MultiProperties#1]
Provide a signed module, let it verify and then it is available for install from the IDE itsself.

See http://wiki.netbeans.org/FaqPluginRequirements

**Comment by lsimedia** [comment]
The (compiled) netbeans plugin is already available at www.netbeans.org (with a valid signature).

http://plugins.netbeans.org/plugin/63739/?show=true

Is it what you need ?

**Comment by markiewb** [comment]
No it is not. If it has a signature, then you did not request a verification. It is not available for install from within the IDE.
- ![2016-07-10_18h39_43](https://cloud.githubusercontent.com/assets/1857095/16714786/39d7d328-46ce-11e6-9c31-5f981bb227b5.png)
- 
  ![2016-07-10_18h50_36](https://cloud.githubusercontent.com/assets/1857095/16714823/45a999b0-46cf-11e6-80ae-ea6b9704488a.png)

**Comment by lsimedia** [comment]
Ok, I understand what you mean.
I submitted the verification of the plugin to netbeans folks.

**Comment by markiewb** [comment]
That looks better now! In a few days your plugin will be verified.

**Comment by lsimedia** [comment]
I just found out that the plugin is now available directly from netbeans (but an old version).
Do you know if I have to ask to verify the plugin each time I will update it ?

**Comment by lsimedia** [comment]
I just found out that the plugin is now published (but an old version), do you know if I should request a verification each time I do an update ?

**Comment by markiewb** [comment]
@lsimedia: Yes, you have to request a validation for each new uploaded version.

**Comment by lsimedia** [comment]
Ok, thanks for your feed-back.
