### ISSUE TITLE
Data loss in Overview panel on File tab

### ISSUE THREAD

**Issue by jkovalsky** [lsimedia/MultiProperties#4]
**Description:**
Changes made to _Name_, _Description_ or _Handler_ fields are not considered as important and do not create Save cookie. Due to this one can close the modified file and loose modifications.

**Environment:**
Apache NetBeans IDE 11.0 (Build incubator-netbeans-release-404-on-20190319)
Updates: Updates available
Java: 1.8.0_201; Java HotSpot(TM) 64-Bit Server VM 25.201-b09
Runtime: Java(TM) SE Runtime Environment 1.8.0_201-b09
System: Linux version 4.15.0-52-generic running on amd64; UTF-8; cs_CZ (nb)

**Steps to reproduce:**
1. Install [MultiProperties](http://plugins.netbeans.org/plugin/63739) plugin to Apache NetBeans IDE 11.0.
2. Open some project and in its _Source Packages_ create new _ML.multiproperties_ file from _Other_ category.
3. Switch to _Visual_ view in Editor and type e.g. _Multi-language dictionary_ into **Description** text area.
4. Close your file in Editor by the **x** button or close NetBeans completely.

**Expected:** User is asked whether the file should be saved or not.
**Actual:** Nothing happens i.e. file is closed or NetBeans exited without any warning.

**Comment by sbodmer** [comment]
Thanks for the report, should be fixed in 1.0.0.6 version (except for the close file save dialog, I don't know how to implements the save when the file is closed...)
